apiVersion: v2
name: pagopa-ecommerce-reporting-functions
description: Microservice that handles reporting for ecommerce
type: application
version: 1.3.5
appVersion: 1.3.5
dependencies:
  - name: microservice-chart
    version: 7.4.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
